name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v4

    # Set up Conda (Miniconda)
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: 'latest'  # You can set a specific version if needed
        python-version: '3.10'
        auto-activate-base: false

    # Update conda environment with config.yml file
    - name: Install dependencies
      run: |
        conda env create --file=config.yml
        conda activate myenv  # Replace 'myenv' with the actual environment name defined in your config.yml

    # Lint with flake8
    - name: Lint with flake8
      run: |
        conda install flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Test with pytest
    - name: Test with pytest
      run: |
        conda install pytest
        pytest
